#############################################################################
# Generated by PAGE version 4.25.1
#  in conjunction with Tcl version 8.6
#  Dec 10, 2019 12:40:23 PM -0800  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 600x450+434+199
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1362 741
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    labelframe $top.lab44 \
        -font TkDefaultFont -foreground black -text Labelframe \
        -background $vTcl(actual_gui_bg) -height 245 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 510 
    vTcl:DefineAlias "$top.lab44" "Labelframe1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab44
    frame $site_3_0.fra45 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 155 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 425 
    vTcl:DefineAlias "$site_3_0.fra45" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.fra45
    entry $site_4_0.ent48 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$site_4_0.ent48" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_0.ent49 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$site_4_0.ent49" "Entry2" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab52 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Label 
    vTcl:DefineAlias "$site_4_0.lab52" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab53 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Label 
    vTcl:DefineAlias "$site_4_0.lab53" "Label2" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but54 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Button 
    vTcl:DefineAlias "$site_4_0.but54" "Button1" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.ent48 \
        -in $site_4_0 -x 140 -y 20 -anchor nw -bordermode ignore 
    place $site_4_0.ent49 \
        -in $site_4_0 -x 140 -y 100 -anchor nw -bordermode ignore 
    place $site_4_0.lab52 \
        -in $site_4_0 -x 40 -y 20 -anchor nw -bordermode ignore 
    place $site_4_0.lab53 \
        -in $site_4_0 -x 60 -y 110 -anchor nw -bordermode ignore 
    place $site_4_0.but54 \
        -in $site_4_0 -x 320 -y 120 -anchor nw -bordermode ignore 
    place $site_3_0.fra45 \
        -in $site_3_0 -x 40 -y 40 -width 425 -relwidth 0 -height 155 \
        -relheight 0 -anchor nw -bordermode ignore 
    labelframe $top.lab46 \
        -font TkDefaultFont -foreground black -text Labelframe \
        -background $vTcl(actual_gui_bg) -height 255 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 510 
    vTcl:DefineAlias "$top.lab46" "Labelframe2" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab46
    frame $site_3_0.fra47 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 165 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 395 
    vTcl:DefineAlias "$site_3_0.fra47" "Frame2" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.fra47
    entry $site_4_0.ent50 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$site_4_0.ent50" "Entry3" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_0.ent51 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$site_4_0.ent51" "Entry4" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab55 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Label 
    vTcl:DefineAlias "$site_4_0.lab55" "Label3" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab56 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Label 
    vTcl:DefineAlias "$site_4_0.lab56" "Label4" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but57 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Button 
    vTcl:DefineAlias "$site_4_0.but57" "Button2" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_4_0.rad58 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text Radio 
    vTcl:DefineAlias "$site_4_0.rad58" "Radiobutton1" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_4_0.rad59 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text Radio 
    vTcl:DefineAlias "$site_4_0.rad59" "Radiobutton2" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.ent50 \
        -in $site_4_0 -x 100 -y 10 -anchor nw -bordermode ignore 
    place $site_4_0.ent51 \
        -in $site_4_0 -x 130 -y 60 -anchor nw -bordermode ignore 
    place $site_4_0.lab55 \
        -in $site_4_0 -x 40 -y 20 -anchor nw -bordermode ignore 
    place $site_4_0.lab56 \
        -in $site_4_0 -x 50 -y 70 -anchor nw -bordermode ignore 
    place $site_4_0.but57 \
        -in $site_4_0 -x 300 -y 120 -anchor nw -bordermode ignore 
    place $site_4_0.rad58 \
        -in $site_4_0 -x 60 -y 130 -anchor nw -bordermode ignore 
    place $site_4_0.rad59 \
        -in $site_4_0 -x 180 -y 130 -anchor nw -bordermode ignore 
    place $site_3_0.fra47 \
        -in $site_3_0 -x 50 -y 50 -width 395 -relwidth 0 -height 165 \
        -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab44 \
        -in $top -x 250 -y 30 -width 510 -relwidth 0 -height 245 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab46 \
        -in $top -x 250 -y 310 -width 510 -relwidth 0 -height 255 \
        -relheight 0 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

